[package]
name = "pg_cranelift"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cranelift-frontend = "^0.108"
cranelift-codegen = "^0.108"
cranelift-module = "^0.108"
cranelift-jit = "^0.108"
cranelift-native = "^0.108"

[build-dependencies]
bindgen = "^0.69"
